name: Deploy Supabase Functions

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase functions deploy webhook --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
      - run: supabase functions deploy check-unanswered --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
